version: "3"
services:
  api:
    image: wendreof/api-ts
    ports:
      - "3050:3050"
    links:
      - link-db
  link-db:
    image: tutum/mongodb
    ports:
      - "27017:27017"
      - "28017:28017"
    environment:
      - AUTH=no
